AWSTemplateFormatVersion: '2010-09-09'

Metadata:
  Template:
    Revision: !Ref Revision

Parameters:
  Revision:
    Description: The git short hash of the repo when the template was applied.
    Type: String

Outputs:
  BucketName:
    Description: S3 bucket for Obsidian data storage
    Value: !Ref Bucket

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled

  User:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: ObsidianS3Sync
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: ReadBucketObjects
                Effect: Allow
                Resource:
                  - !GetAtt Bucket.Arn
                Action:
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
              - Sid: ReadWriteObjects
                Effect: Allow
                Resource:
                  - !Sub "${Bucket.Arn}/*"
                Action:
                  - s3:AbortMultipartUpload
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:GetObjectAttributes
                  - s3:ListMultipartUploadParts
                  - s3:PutObject
